### ISSUE TITLE
BehaviourAnalysis Error

### ISSUE THREAD

**Issue by mhanne0915** [brad-accuvant/cuckoo-modified#75] opened 2015-06-05 00:18 UTC
I run this sample 13a44a9970c6c311a08cae357a545972, and i found that it failed to process (process.py) the logs because there's something wrong on parsing the data in behaviour.py. 

Here's the error:

ERROR:lib.cuckoo.core.plugins:Failed to run the processing module "BehaviorAnalysis":
Traceback (most recent call last):
  File ".../utils/../lib/cuckoo/core/plugins.py", line 194, in process
    data = current.run()
  File ".../utils/../modules/processing/behavior.py", line 1088, in run
    behavior["processes"] = Processes(self.logs_path).run()
  File ".../utils/../modules/processing/behavior.py", line 376, in run
    current_log = ParseProcessLog(file_path)
  File ".../utils/../modules/processing/behavior.py", line 55, in **init**
    self.parse_first_and_reset()
  File ".../utils/../modules/processing/behavior.py", line 87, in parse_first_and_reset
    self.parser.read_next_message()
  File ".../utils/../lib/cuckoo/common/netlog.py", line 79, in read_next_message
    data = self.handler.read(4)
  File "../utils/../modules/processing/behavior.py", line 100, in read
    raise EOFError(

**Comment by therealdreg** [comment] 2015-06-05 09:25
Confirmed, I have the same problem.

And also I have this error:

015-06-05 05:21:21,431 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 413, in run
    self.process_results()
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 362, in process_results
    RunSignatures(task_id=self.task.id, results=results).run()
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/core/plugins.py", line 391, in run
    self._check_signature_version(sig) and (not sig.filter_analysistypes or self.results["target"]["category"] in sig.filter_analysistypes)]
  File "/home/cuckoo/cuckoo-modified/modules/signatures/deletes_self.py", line 31, in __init__
    processes = self.results["behavior"]["processes"]
KeyError: 'behavior'

**Comment by ghost** [comment] 2015-06-05 11:38
Analysis becomes frozen.. 
.....
        if not buf or len(buf) != length:
            raise EOFError()
....

**Comment by brad-sp** [comment] 2015-06-05 13:07
Can someone send me the <pid>.bson for the analysis?  I'm not able to reproduce this at all.

**Comment by mhanne0915** [comment] 2015-06-05 14:33
brad, here's the link for bson log of 13a44a9970c6c311a08cae357a545972:
http://s000.tinyupload.com/?file_id=13188344633937014876
note: run in windows 7 64-bit VM

anyway, sorry for the upload there are ads on it cause it's free ;)

**Comment by brad-sp** [comment] 2015-06-05 15:18
It seems that one of the logged processes did not report any environment info -- I have an idea of what could potentially cause that -- our initial log flush will hold back on the last log in order to avoid duplicates, but it shouldn't hold back **notification** logs like new process/thread/environ as those won't ever be duplicated.  I guess no subsequent flush happened in that process, so it missed the environment info despite the loq() call succeeding (it output the format of the to-be-sent environ info into the log).

I should have a fix shortly, thanks!

**Comment by brad-sp** [comment] 2015-06-05 15:24
Can you try with the latest commit? Thanks

**Comment by mhanne0915** [comment] 2015-06-05 16:44
Hi brad, just finished the testing and your patch fixed the problem. Many thanks ;)

**Comment by supahal** [comment] 2015-06-08 02:46
thank you brad.

**Comment by ghost** [comment] 2015-06-08 03:24
Hi Brad,

Bson logs uploaded here:  http://s000.tinyupload.com/?file_id=64771736517797952283
After migrating to the latest release. Im still experiencing EOFError during behavioral analysis.

**Comment by therealdreg** [comment] 2015-06-08 11:07
Now works fine, thx Brad :-)

**Comment by brad-sp** [comment] 2015-06-08 14:25
supahal: I think your instance of this problem is related to the other issue you've posted -- for some reason your logs are corrupted.  For instance, environment info is completely missing from one of your logs, even though further API logs exist.  I'll close this issue and we can work on your specific problem in the other thread.

**Closed as completed by brad-sp** 2015-06-08 14:25 UTC
