### ISSUE TITLE
Problems with int value in utils.py

### ISSUE THREAD

**Issue by dforce** [brad-accuvant/cuckoo-modified#58] opened 2015-05-18 09:49 UTC
When analyzing a dll I receive following error :
Traceback (most recent call last):
  File "/data/virtualenvs/env_modified/cuckoo/lib/cuckoo/core/plugins.py", line 194, in process
    data = current.run()
  File "/data/virtualenvs/env_modified/cuckoo/modules/processing/behavior.py", line 1081, in run
    for call in process["calls"]:
  File "/data/virtualenvs/env_modified/cuckoo/modules/processing/behavior.py", line 182, in next
    return self.cacheless_next()
  File "/data/virtualenvs/env_modified/cuckoo/modules/processing/behavior.py", line 159, in cacheless_next
    self.wait_for_lastcall()
  File "/data/virtualenvs/env_modified/cuckoo/modules/processing/behavior.py", line 137, in wait_for_lastcall
    if not self.parser.read_next_message():
  File "/data/virtualenvs/env_modified/cuckoo/lib/cuckoo/common/netlog.py", line 201, in read_next_message
    self.handler.log_call(context, apiname, category, arguments)
  File "/data/virtualenvs/env_modified/cuckoo/modules/processing/behavior.py", line 243, in log_call
    returnval] + arguments)
  File "/data/virtualenvs/env_modified/cuckoo/modules/processing/behavior.py", line 302, in _parse
    pretty = pretty_print_arg(category, api_name, arg_name, argument["value"])
  File "/data/virtualenvs/env_modified/cuckoo/lib/cuckoo/common/utils.py", line 1130, in pretty_print_arg
    val = int(arg_val, 16)
ValueError: invalid literal for int() with base 16: '0x-7ffffffe'

File can be found here
https://www.virustotal.com/en/file/86dd4792638883024ad4402dce75f358dd531b5d00c3994ba290e21fc9c638e4/analysis/

Can you solve this problem ?

Thanks

**Comment by brad-sp** [comment] 2015-05-18 12:44
No problem here, and that line number doesn't even match up with the text of the line being reported as the problem.  Are you running the latest version?

**Comment by dforce** [comment] 2015-05-18 12:54
Yes - that latest version on github.

**Comment by brad-sp** [comment] 2015-05-18 12:55
Can you pastebin your copy of utils.py somewhere?

**Comment by dforce** [comment] 2015-05-18 12:59
Can I send you mail with my copy ?

**Comment by dforce** [comment] 2015-05-18 13:01
If that doesn't work I will send you a link where to find it.

**Comment by brad-sp** [comment] 2015-05-18 13:02
Sure that's fine.

**Comment by dforce** [comment] 2015-05-18 14:39
Here is the link to my utils.py
https://app.box.com/s/y2usm4awrqwoilmametxw4nz49yhqae1

**Comment by dforce** [comment] 2015-05-18 14:42
Second time I ran the file it gave the error at line 1159 in utils.py

**Comment by brad-sp** [comment] 2015-05-18 15:27
This should be fixed now with https://github.com/brad-accuvant/cuckoo-modified/commit/d61ee2080c239b95c4206f4bf85667828f78fb45 Give that a try.

**Comment by dforce** [comment] 2015-05-18 16:42
It didn't resolved the problem.
Here is my traceback

Traceback (most recent call last):
  File "/data/virtualenvs/env_modified/cuckoo/lib/cuckoo/core/plugins.py", line 194, in process
    data = current.run()
  File "/data/virtualenvs/env_modified/cuckoo/modules/processing/behavior.py", line 1081, in run
    for call in process["calls"]:
  File "/data/virtualenvs/env_modified/cuckoo/modules/processing/behavior.py", line 182, in next
    return self.cacheless_next()
  File "/data/virtualenvs/env_modified/cuckoo/modules/processing/behavior.py", line 159, in cacheless_next
    self.wait_for_lastcall()
  File "/data/virtualenvs/env_modified/cuckoo/modules/processing/behavior.py", line 137, in wait_for_lastcall
    if not self.parser.read_next_message():
  File "/data/virtualenvs/env_modified/cuckoo/lib/cuckoo/common/netlog.py", line 195, in read_next_message
    self.handler.log_call(context, apiname, category, arguments)
  File "/data/virtualenvs/env_modified/cuckoo/modules/processing/behavior.py", line 243, in log_call
    returnval] + arguments)
  File "/data/virtualenvs/env_modified/cuckoo/modules/processing/behavior.py", line 302, in _parse
    pretty = pretty_print_arg(category, api_name, arg_name, argument["value"])
  File "/data/virtualenvs/env_modified/cuckoo/lib/cuckoo/common/utils.py", line 1159, in pretty_print_arg
    val = int(arg_val, 16)
ValueError: invalid literal for int() with base 16: '0x-7ffffffe'

**Comment by dforce** [comment] 2015-05-18 18:40
When you run the file, do you also see the error ?

**Comment by dforce** [comment] 2015-05-19 08:27
I also have other files which report this error.
This is only happening when running 32+PE within a 64bit vm. 
Problem is also that te analysis is paused and no results are transfered to mongodb.

Can this be solved ?

**Comment by brad-sp** [comment] 2015-05-19 13:08
Can you give me a hash of a non-DLL exhibiting the problem?

**Comment by dforce** [comment] 2015-05-19 14:01
Link to file on virustotal
https://www.virustotal.com/en/file/5161cdafd0c6d79616d775f79214b2e7e3ad13de71db63e9fa6bfc448ba4084b/analysis/

Running it within a Win XP 64bit vm

**Comment by brad-sp** [comment] 2015-05-19 14:59
I'm unable to reproduce with that one as well.  Did you make sure to restart cuckoo.py?  Can you give me the .bson file from the logs directory of the analysis, so I can try reproducing it here with a re-processing of the log?

**Comment by dforce** [comment] 2015-05-19 15:27
Link to log file
https://app.box.com/s/yq75b9hrehuappwcerc92kgb0vru4h31

**Comment by brad-sp** [comment] 2015-05-19 15:44
Check again to make sure you're using the latest version.  I get no errors when re-running processing with your .bson log, and I've uploaded the same binary to another sandbox running a recent version which also had no errors.

**Closed as completed** 2015-05-19 15:45 UTC

**Comment by dforce** [comment] 2015-05-19 16:23
I reinstalled my virtualenv.
Downloaded the latest version but still got the same error.

Did you tested it within a Win XP 64 bit ?

**Comment by brad-sp** [comment] 2015-05-19 16:25
It wouldn't make a difference for this, as the only thing being processed on is the bson log

**Comment by dforce** [comment] 2015-05-19 16:28
Does it has something to do with bson because bson is now a part of pymongo ?

**Comment by brad-sp** [comment] 2015-05-19 16:32
It shouldn't, since the previous problem was in conversion of the values after they were interpreted by bson.  The new code prevents there being any negative int/long values by masking off the upper bits as appropriate.  If your bson parser is returning something other than an int or a long for the values, then that would be an issue, but I don't see that happening.

**Comment by dforce** [comment] 2015-05-19 16:57
I am a bit lost now.
Can't find the problem on my machine.

**Comment by mpars0ns** [comment] 2015-08-29 18:35
I was having this problem as well today and I did this on the command line (ubuntu 14.04 server) 
sudo pip install --upgrade bson
Downloading/unpacking bson
  Downloading bson-0.4.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/bson/setup.py) egg_info for package bson

Requirement already up-to-date: pytz>=2010b in /usr/local/lib/python2.7/dist-packages (from bson)
Requirement already up-to-date: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from bson)
Installing collected packages: bson
  Running setup.py install for bson

Successfully installed bson
Cleaning up...

tried process.py on the report that was having issues and everything was processed correctly.
Hope that helps

**Comment by KillerInstinct** [comment] 2015-08-30 01:48
IIRC you shouldn't be installing bson as it's included with mongodb/pymongo.

**Comment by mpars0ns** [comment] 2015-08-31 11:26
Well I have mongo installed. It is the one provided by Ubuntu, I haven't tried it with the latest version. I also have configured my instance of cuckoo to use ElasticSearch. I was running into the same error @dforce was having when he reported this issue. I tried upgrading the bson that was already installed with python. I will try and remove it, and download the latest version of MongoDB and see if that works as well. Until I can do that I will rely on the python bson module.
